GET http://127.0.0.1:3000/items

###

GET http://127.0.0.1:3000/items/shop/test

###

GET http://127.0.0.1:3000/items/1

###

POST  http://127.0.0.1:3000/items/test
X-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20ifQ.OntVj6u8x_LkKSS_R76aE03-SgTxmEBcMGng3TivPiA
Content-Type: application/json

{
  "itemName": "test",
  "itemPrice": 12,
  "itemDescription": "This is a description"
}
