CREATE DATABASE eshop;

\c eshop;

CREATE TABLE users (
  username VARCHAR PRIMARY KEY,
  email VARCHAR NOT NULL,
  password VARCHAR NOT NULL,
  createdAt DATE NOT NULL default CURRENT_TIMESTAMP
);

CREATE TABLE shops (
  shopName VARCHAR PRIMARY KEY,
  shopImage VARCHAR NOT NULL,
  shopDescription VARCHAR NOT NULL,
  shopDate DATE NOT NULL default CURRENT_TIMESTAMP,
  owner VARCHAR NOT NULL,
  CONSTRAINT user_shop FOREIGN KEY (owner) REFERENCES users(username) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE shopsRates (
  shopName VARCHAR NOT NULL,
  username VARCHAR NOT NULL,
  rate SMALLINT NOT NULL,
  PRIMARY KEY (shopName, username),
  CONSTRAINT shop_rate FOREIGN KEY (shopName) REFERENCES shops(shopName) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT user_shop_rate FOREIGN KEY (username) REFERENCES users(username) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE items (
  itemID SERIAL PRIMARY KEY,
  itemName VARCHAR NOT NULL,
  itemImage VARCHAR NOT NULL,
  itemPrice INT NOT NULL,
  itemDescription VARCHAR NOT NULL,
  itemDate DATE NOT NULL default CURRENT_TIMESTAMP,
  shop VARCHAR NOT NULL,
  CONSTRAINT shop_item FOREIGN KEY (shop) REFERENCES shops(shopName) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE itemsRates (
  itemID INT NOT NULL,
  username VARCHAR NOT NULL,
  rate SMALLINT NOT NULL,
  PRIMARY KEY (itemID, username),
  CONSTRAINT item_rate FOREIGN KEY (itemID) REFERENCES items(itemID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT user_item_rate FOREIGN KEY (username) REFERENCES users(username) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE itemsComments (
  commentID SERIAL PRIMARY KEY,
  commentValue VARCHAR NOT NULL,
  commentDate DATE NOT NULL default CURRENT_TIMESTAMP,
  itemID INT NOT NULL,
  username VARCHAR NOT NULL,
  CONSTRAINT item_comment FOREIGN KEY (itemID) REFERENCES items(itemID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT user_item_comment FOREIGN KEY (username) REFERENCES users(username) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE carts (
  cartID SERIAL PRIMARY KEY,
  cartDate DATE NOT NULL default CURRENT_TIMESTAMP,
  username VARCHAR NOT NULL,
  CONSTRAINT user_cart FOREIGN KEY (username) REFERENCES users(username) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE cartsItems (
  cartItemID SERIAL PRIMARY KEY,
  amount SMALLINT NOT NULL,
  itemID INT NOT NULL,
  cartID INT NOT NULL,
  CONSTRAINT item_cart FOREIGN KEY (itemID) REFERENCES items(itemID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT cart_item FOREIGN KEY (cartID) REFERENCES carts(cartID) ON DELETE CASCADE ON UPDATE CASCADE
);
